services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - default

  web:
    build: .
    command: uvicorn back.1lecture.src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default

  celery:
    build: .
    command: celery -A back.1lecture.src.celery_app:app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app

  celery-beat:
    build: .
    command: celery -A back.1lecture.src.celery_app:app beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
    networks:
      - default
    working_dir: /app

  flower:
    build: .
    command: celery -A back.1lecture.src.celery_app:app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    networks:
      - default
    working_dir: /app

volumes:
  postgres_data:
  redis_data:
